# Maciej Buszka

CFLAGS = -g -std=gnu99 -Wall -Wextra -pthread
LDFLAGS = -pthread -lrt
CC=gcc

all : ex2a ex2b ex3 ex4 ex5 ex6 # philosophers_processes # sem_test

ex2a :

ex2b :

ex3 : barrier.o

barrier.o : barrier.h

ex4 :

ex5 : list.o

list.o : list.h

ex6 :

clean :
	rm *.o ex2a ex2b ex3 ex4 ex5 ex6
